name: Generate Screenshots

on:
  pull_request:
    paths:
      - '**/game.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Fetch PR branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
          git checkout -b pr-branch
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer sharp
          
      - name: Generate Screenshots
        run: node .github/scripts/take-screenshots.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug Info
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "Changed files:"
          git diff --name-only HEAD^
          echo "Git status:"
          git status
          
      - name: Commit Screenshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Add screenshots for updated games"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_HEAD_REF} --force
          else
            echo "No changes to commit"
          fi

