name: Take Screenshots

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  take_screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # Important for git diff

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install puppeteer sharp

    - name: Get changed game.json files
      id: changed-files
      run: |
        if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
          changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep 'game.json' | tr '\n' ' ')
        else
          changed_files=$(git diff --name-only HEAD~1 | grep 'game.json' | tr '\n' ' ')
        fi
        echo "CHANGED_FILES=$changed_files" >> $GITHUB_ENV
        echo "Changed files: $changed_files" # debug
    - name: Take screenshots
      run: node .github/scripts/take-screenshots.js

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update game screenshots and game.json files"