name: Generate Screenshots

on:
  pull_request:
    paths:
      - '**/game.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer sharp
          
      - name: Debug Git Info
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Current branch: $(git branch --show-current)"
          echo "Remote URL: $(git remote get-url origin)"
          echo "Changed files:"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          
      - name: Generate Screenshots
        run: node .github/scripts/take-screenshots.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          
      - name: Commit Screenshots
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Add screenshots for updated games"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin HEAD
          fi

