name: Take Screenshots

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  take_screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install puppeteer sharp

    - name: Get changed files (explicit)
      id: changed-files
      run: |
        if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
          # Get files modified in the pull request
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.ref }}...${{ github.sha }} | grep 'game.json' | tr '\n' ' ')
        else
          # Get files modified in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD~1...HEAD | grep 'game.json' | tr '\n' ' ')
        fi
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
        echo "Changed files: $CHANGED_FILES" # Debug output

    - name: Take screenshots
      run: node .github/scripts/take-screenshots.js

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update game screenshots and game.json files"