name: Generate Screenshots

on:
  pull_request:
    paths:
      - '**/game.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fetch PR
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
          git checkout -b pr-branch
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-changes
          git merge pr-changes
          
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer sharp
          
      - name: Debug Git Info
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Changed files:"
          git diff --name-only origin/main HEAD
          
      - name: Generate Screenshots
        run: node .github/scripts/take-screenshots.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
      - name: Commit Screenshots
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Add screenshots for updated games"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.head_ref }}

