name: Generate Screenshots

on:
  push:
    paths:
      - '**/game.json'

jobs:
  screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install puppeteer sharp

    - name: Get changed files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD~1...HEAD | grep 'game.json' || true)
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
        echo "Changed files: $CHANGED_FILES"

    - name: Generate Screenshots
      run: node .github/scripts/take-screenshots.js

    - name: Commit changes
      if: env.CHANGED_FILES != ''
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update game screenshots and game.json files"